# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='date_created',
        ),
        migrations.AddField(
            model_name='plant',
            name='shade_tolerance',
            field=models.IntegerField(blank=True, default=0, help_text='How much shade can the plant tolerate (0-4)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_preference',
            field=models.IntegerField(blank=True, default=0, help_text='How much sun does the plant prefer (0-2)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_humidity',
            field=models.DecimalField(decimal_places=2, help_text='Ideal humidity (between 0 and 1)', max_digits=3),
        ),
    ]
