# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_moisturelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=True)),
                ('moisture_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.MoistureLog')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('num_seconds_open', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='plantcollection',
            name='name',
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='watering_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.WateringLog'),
        ),
        migrations.AddField(
            model_name='plantcollection',
            name='plants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.PlantInstance'),
        ),
    ]
