# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20160316_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinstance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
