# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_auto_20160316_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinstance',
            name='sensor_offset_max',
            field=models.IntegerField(default=0, help_text='Humidity sensor offset for calibration (max)'),
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='sensor_offset_min',
            field=models.IntegerField(default=0, help_text='Humidity sensor offset for calibration (min)'),
        ),
    ]
