# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_auto_20160316_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='moisturelog',
            name='plant_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.PlantInstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateringlog',
            name='plant_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.PlantInstance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_humidity',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH')], max_length=100),
        ),
    ]
