# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20160316_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='shade_tolerance',
            field=models.IntegerField(blank=True, default=0, help_text='How much shade can the plant tolerate (1-3)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun_preference',
            field=models.IntegerField(blank=True, default=0, help_text='How much sun does the plant prefer (1-2)'),
        ),
    ]
