# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20160330_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='shade_tolerance',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('LIGHT', 'LIGHT'), ('PERMANENT', 'PERMANENT')], help_text='How much shade the plant can tolerate', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sun_preference',
            field=models.CharField(blank=True, choices=[('MINIMAL', 'MINIMAL'), ('FULL', 'FULL')], help_text='How much sun the plant prefers', max_length=100),
        ),
    ]
