# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_auto_20160330_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinstance',
            name='pin_number',
            field=models.IntegerField(help_text='Pin number of the humidity sensor', unique=True),
        ),
    ]
